import json
from typing import Generator, Any
from openai import OpenAI
from app.agent.mcp_adapter import MCPAdapter

class StreamToolBuffer:
    """Accumulates streaming tool call chunks into OpenAI-formatted payloads."""
    
    def __init__(self) -> None:
        self._buffer: dict[int, dict[str, str]] = {}

    # Process tool_call deltas
    def process_deltas(self, tool_calls: list[Any]) -> None:
        for tool_call in tool_calls:
            idx = tool_call.index
            if idx not in self._buffer:
                self._buffer[idx] = {"id": "", "name": "", "arguments": ""}
            
            if tool_call.id:
                self._buffer[idx]["id"] += tool_call.id
            if tool_call.function:
                if tool_call.function.name:
                    self._buffer[idx]["name"] += tool_call.function.name
                if tool_call.function.arguments:
                    self._buffer[idx]["arguments"] += tool_call.function.arguments

    @property
    def has_calls(self) -> bool:
        return bool(self._buffer)

    def build_tool_calls(self) -> list[dict[str, Any]]:
        return [
            {
                "id": self._buffer[i]["id"],
                "type": "function",
                "function": {
                    "name": self._buffer[i]["name"],
                    "arguments": self._buffer[i]["arguments"]
                }
            }
            for i in sorted(self._buffer.keys())
        ]


class CompletionHandler:
    """Handles OpenAI completions, tool call accumulation, and execution loops."""
    
    def __init__(self, client: OpenAI, model_name: str, mcp_adapter: MCPAdapter) -> None:
        self.client = client
        self.model_name = model_name
        self.mcp = mcp_adapter

    # Stream mode ON  -> The response is streamed in real-time as it is generated by the AI
    def generate_stream(self, messages: list[dict[str, Any]], tools: list[dict]) -> Generator[str, None, None]:
        kwargs: dict[str, Any] = {"model": self.model_name, "messages": messages, "stream": True}
        if tools:
            kwargs["tools"] = tools

        stream = self.client.chat.completions.create(**kwargs)  # type: ignore
        buffer = StreamToolBuffer()

        for chunk in stream:
            delta = chunk.choices[0].delta if chunk.choices else None
            if not delta:
                continue

            if delta.content:
                yield delta.content

            if delta.tool_calls:
                buffer.process_deltas(delta.tool_calls)

        if buffer.has_calls:
            assistant_tool_calls = buffer.build_tool_calls()
            messages.append({"role": "assistant", "tool_calls": assistant_tool_calls})

            for tool_call in assistant_tool_calls:
                yield from self._execute_and_append_tool(messages, tool_call)

            yield from self.generate_stream(messages, tools)

    # Stream mode OFF -> The complete response is returned all at once
    def generate_static(self, messages: list[dict[str, Any]], tools: list[dict]) -> Generator[str, None, None]:
        kwargs: dict[str, Any] = {"model": self.model_name, "messages": messages, "stream": False}
        if tools:
            kwargs["tools"] = tools

        response = self.client.chat.completions.create(**kwargs)  # type: ignore
        message = response.choices[0].message

        if message.tool_calls:
            tool_calls = [
                {
                    "id": tool_call.id,
                    "type": "function",
                    "function": {"name": tool_call.function.name, "arguments": tool_call.function.arguments}
                }
                for tool_call in message.tool_calls
            ]
            messages.append({"role": "assistant", "content": message.content, "tool_calls": tool_calls})

            for tool_call in tool_calls:
                yield from self._execute_and_append_tool(messages, tool_call)

            yield from self.generate_static(messages, tools)
        else:
            yield message.content or ""

    def _execute_and_append_tool(self, messages: list[dict[str, Any]], tool_call: dict[str, Any]) -> Generator[str, None, None]:
        fn_name = tool_call["function"]["name"]
        raw_args = tool_call["function"]["arguments"]
        
        try:
            args = json.loads(raw_args) if raw_args else {}
        except json.JSONDecodeError:
            args = {}

        yield f"\n\n[dim]Executing tool: {fn_name}...[/dim]\n\n"
        result = self.mcp.execute_tool(fn_name, args)

        messages.append({
            "role": "tool",
            "tool_call_id": tool_call["id"],
            "content": result
        })